obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[x0, y0], [x1, y1], [x2, y2], [x3, y3]]
inflation_radius: 0.55
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: PointCloud2, topic: velodyne_points, marking: true, clearing: true}
